---
apiVersion: v1
kind: Service
metadata:
  name: postgresapp-service
  labels:
    author: hemana
spec:
  type: LoadBalancer
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgresapp
...
