---
apiVersion: v1
kind: Service
metadata:
  name: redisapp-service
  labels:
    author: hemana
spec:
  type: LoadBalancer
  ports:
    - targetPort: 6380
      port: 6380
  selector:
    name: redisapp
...
