---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels: 
   author: samba3
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redisapp
  template:
    metadata:
      name: redisapp-pod
      labels:
        name: redisapp
    spec:
      containers:
        - name: myredis-app
          image: redis
...
