---
apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    author: hemana
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    name: resultapp
...
