---
apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    author: hemana
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    name: votingapp
...



      

